applications:
  - name: "echo-server"
    path: "/bin/sh"
    args: ["-c", "while true; do echo 'Hello from echo-server' $(date); sleep 2; done"]
    env:
      - "APP_NAME=echo-server"
    stop_signal: "SIGTERM"
  - name: "counter"
    path: "/bin/sh"
    args: ["-c", "i=0; while true; do echo 'Counter: '$i; i=$((i+1)); sleep 1; done"]
    env:
      - "APP_NAME=counter"
    stop_signal: "SIGINT"
  - name: "error-test"
    path: "/bin/sh"
    args: ["-c", "echo 'Starting up...'; sleep 2; echo 'Simulating error'; exit 42"]
    env:
      - "APP_NAME=error-test"
    stop_signal: "SIGTERM"

listen: "localhost:8080"

tailscale:
  enabled: false
  name: "tailon-server"
  state_dir: "/tmp/tailscale-state"

# Security configuration (NEW!)
security:
  # The default role which should be assigned in cases where a more specific
  # role is not specified as part of the Tailscale capabilities for the user.
  default_role: admin
  
  # Restrict anonymous access to specific IP ranges (optional)
  # Uncomment and configure for additional security
  # allowed_ips:
  #   - "127.0.0.1"        # localhost only
  #   - "192.168.1.0/24"   # local network
  #   - "10.0.0.0/8"       # private network
  
  # Hide environment variables in API responses
  # Set to true to prevent leaking sensitive environment variables
  hide_env_vars: false
